### PR TITLE
Kubernetes cron jobs

### PR DESCRIPTION
**Pull request by bulkware**
- The pod name is not retrieved since I couldn't figure out how I should match jobs and pods.
- There probably is no need to collect any other data than the job name for discovery. I did not figure out just how exactly.
- Check response after we merge ZabbixAPI refactoring.

### CODE REVIEW

**Comment by bulkware** [comment]
I outputted listings for pods and jobs and modified those files to hold every key and value in their own lines. Then I compared these files using grep to see if there were any correlations between these files. The only thing I found out was that the name of my cron job can be found from the pods file, but I fail to see what good it does since the name is "hello". I did this so I could see if there would be any hash sum or ID that would link these two things together.

**Comment by kompa3** [comment]
Sorry, I guess I won't be able to review this at the moment ..

**Comment by bulkware** [comment]
Should I refactor this so that the "cron jobs" section has two main parts, discovery and trapper data sending from metrics? Kind of like the upcoming ticket to refactor the "msg_integration_discovery_v2"?

**Comment by sapajune** [comment]
> Should I refactor this so that the "cron jobs" section has two main parts, discovery and trapper data sending from metrics? Kind of like the upcoming ticket to refactor the "msg_integration_discovery_v2"?

Sounds good.

**Comment by sapajune** [comment]
I'm a bit confused about the Kubernetes Python APIs atm. Do you know what's the difference between CronJob and Batch APIs?

**Comment by bulkware** [comment]
> 
> 
> I'm a bit confused about the Kubernetes Python APIs atm. Do you know what's the difference between CronJob and Batch APIs?

In my development environment I created two cron jobs and received the data using the Batch API. Did I assume incorrectly? I don't think there is a way to list jobs using the v1 API since jobs can only be listed using the Batch API. But of course, this doesn't mean we cannot use a more updated version of the API. Maybe we can discuss this tomorrow in a conference call?

**Comment by sapajune** [comment]
> > I'm a bit confused about the Kubernetes Python APIs atm. Do you know what's the difference between CronJob and Batch APIs?
> 
> In my development environment I created two cron jobs and received the data using the Batch API. Did I assume incorrectly? I don't think there is a way to list jobs using the v1 API since jobs can only be listed using the Batch API. But of course, this doesn't mean we cannot use a more updated version of the API. Maybe we can discuss this tomorrow in a conference call?

Yeah. Let's get back to this tomorrow. Note also that targeted use is pre-1.17 Kubernetes (not sure if API doc actually shows compatibility information).

**Comment by sapajune** [comment]
Is this now ready? Code looks good but is it still missing something that we discussed about?

**Comment by bulkware** [comment]
> 
> 
> Is this now ready? Code looks good but is it still missing something that we discussed about?

Not quite ready just yet, I will post a new message after I complete this :)

**Comment by bulkware** [comment]
> 
> 
> > Is this now ready? Code looks good but is it still missing something that we discussed about?
> 
> Not quite ready just yet, I will post a new message after I complete this :)

I think this has now all the discussed things except the discovery/metric refactoring. That would be a copy-and-paste from the same data retrieval and checks for multiple lines. Might not be ideal.

**Review by sapajune — APPROVED** [review]

**Pull request merged**
